### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by FrancisBases**
Dear Sam,
Here goes the little document.
I hope it's ok. Do feel free to change it as will.
Best,
Franc

### CODE REVIEW

**Review by hershaw — CHANGES_REQUESTED** [review]
Haven't looked at the content yet. What you can do is just write this directly on the wiki and let me know when it's done and we'll iterate from there if need be.  You can upload the images to imugr and link to them directly in the markdown which saves space in the repo by not uploading binaries :)

**Comment by FrancisBases** [comment]
Ok, can you give me more details on how to write directly on the wiki i am not very experienced in it uhuh

Regarding the images they are available in http://imgur.com/a/Akp3R and http://imgur.com/0pCkIiq but the markdown didn't work so well, so i just added them. Again i don't do this very often so bear with me. :) thank you

**Comment by hershaw** [comment]
No problem at all! This whole thing is a learning experience. You can just click on the Wiki tab up top and write the same markdown that you are writing in the README. pretty nice, right?

**Comment by FrancisBases** [comment]
Yes, indeed! I already did it in my repo https://github.com/FrancisBase/setup/wiki . Now the last piece of the puzzle how to properly link the imgur images.

**Comment by FrancisBases** [comment]
Ok i will do this after the academy weekend, i'm sure it's a simple detail. In the meanwhile thank you very much.

**Comment by hershaw** [comment]
There's an example of how to link the images in the README.md of this repo. It looks like this

```
![launch jupyter notebook](https://i.imgur.com/SFeVsT6.png)
```

Notice the `!` at the beginning. No need to wait until after the academy, you're 90% of the way there already!

**Comment by FrancisBases** [comment]
Here it is!! https://github.com/FrancisBase/setup/wiki
Thank you for your support, without it i wouldn't be so fast setting the wiki, it's nice to get it done! And i have learned in the process how to build wikis! 

If you can check it out (not hurry i know you are busy!) and give me feedback. Thank you!!

**Pull request closed without merging**
